# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05447286200d9596cb31e31114634575ac8cc25156dfdfdd6d4d211b73576c96247eda49841914b24fb4bf08f3738b5dc5f74f6b785b1df45df60c239d072093

test:
  secret_key_base: 97da6be81fa73ef05d4e51901a661e102e22273e8e67010443d1bfa9df025ed33e86fb5f9710d7e01e21fef903ca7d3abb8ce268d920892b3af621089ebb924c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
